version: "3.7"
services:
  app:
    working_dir: "${CONTAINER_ROOT}"
    build:
      context: docker
      dockerfile: Dockerfile
    volumes:
      - .:${CONTAINER_ROOT}
    links:
      - redis
    ports:
      - ${WEB_PORT}:80
    environment:
      - WEBROOT=${CONTAINER_ROOT}/public
      - ROOT=${CONTAINER_ROOT}
      - NGINX_SERVER_NAME=${NGINX_SERVER_NAME}
      - PUID=${DOCKER_HOST_UID}
      - PGID=${DOCKER_HOST_GID}
      - XDEBUG_ON=${XDEBUG_ON}

  redis:
    image: redis:5.0-buster
